### PR TITLE
README: Done in v2

### PR DESCRIPTION
**Pull request by minminlittleshrimp**
- Add introduction, overview
- Add model arch detail, for autoencoder need more info

### CODE REVIEW

**Comment by minminlittleshrimp** [comment]
This should not be merged yet, dataset is not FaceA -> MNIST, also layers in DCGAN is not yet defined??? :confused:

**Comment by Requiem5032** [comment]
Encoder:
- The input should be (batch_size, 1, 28, 28)
- The output of the first conv layer of encoder is (batch_size, 64, 14, 14)
- The output for the second conv layer is (batch_size, 128, 7, 7)
- Flatten the output which makes it (batch_size, 6272)
- Finally, the linear layer will map it to (batch_size, 7)

Decoder:
- The input is (batch_size, 7)
- The output for the linear layer is (batch_size, 6272)
- Reshape the ouput of linear layer which makes it (batch_size, 128, 7, 7)
- The output of the first transposed conv is (batch_size, 64, 14, 14)
- Finally output of the second transposed conv is (batch_size, 1, 28, 28)
- The Tanh activation is to make the output have the range of (-1 ,1)

**Comment by minminlittleshrimp** [comment]
Why close? 😃

**Comment by Requiem5032** [comment]
Wrong button 〜⁠(⁠꒪⁠꒳⁠꒪⁠)⁠〜

**Pull request merged**
