### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haoidk20002**
The slides are completed. You can edit the slide if you see something that need to be dealt.

### CODE REVIEW

**Comment by Requiem5032** [comment]
You should split the model architecture of GAN into a generator and a discriminator. With the way you have it connected like that it seems like GAN is one singular model which is obviously not true.

**Comment by Requiem5032** [comment]
And please enable edit mode for the slides, it is currently in view only mode.

**Comment by haoidk20002** [comment]
> And please enable edit mode for the slides, it is currently in view only mode.

Done.

**Comment by haoidk20002** [comment]
> GAN is one singular model

Done

**Pull request merged**
